version: '3'
services:
  mongo:
    container_name: mongo_for_todo
    image: mongo
    restart : always
    env_file:
      - .env.local
    ports:
      - "27017:27017"
    volumes:
      - "mongo_for_todo/data/db"